### ISSUE TITLE
rotate 부분 

### ISSUE THREAD

**Issue by Taeu** [cyc1am3n/Problem_Solving#1]
대영님 별건 아니지만
 lec06-algorithm.md >> rotate 부분 result 주석이 조금 다른 거 같아요
실행시켜보면 

// 0 1 2 3 4 5
// 2 3 4 5 0 1
// 3 4 5 0 1 2
// 4 5 0 1 2 3
// 5 0 1 2 3 4

에서 -> 

// 1 2 3 4 5 0
// 2 3 4 5 0 1
// 3 4 5 0 1 2
// 4 5 0 1 2 3
// 5 0 1 2 3 4
// 0 1 2 3 4 5

이렇게 수정이 필요할 것 같습니다 :)

**Comment by cyc1am3n** [comment]
오!! 감사합니다ㅋㅋㅋ 수정했습니다~~
